const ProgressReportGenerator = () => {
  const [reportData, setReportData] = React.useState(null);
  const [isGenerating, setIsGenerating] = React.useState(false);

  const generateReport = () => {
    setIsGenerating(true);
    
    let data = {
      user: { name: 'John Doe', email: 'john.doe@school.edu' },
      courses: [],
      quizzes: [],
      assignments: [],
      achievements: [],
      stats: { totalHours: 24.5, currentStreak: 7, completedCourses: 3 }
    };

    if (window.Database) {
      data.courses = window.Database.getAllCourses() || [];
      data.quizzes = window.Database.getAllQuizzes() || [];
      data.assignments = window.Database.getAllAssignments() || [];
    }

    setTimeout(() => {
      setReportData(data);
      setIsGenerating(false);
    }, 1000);
  };

  const printReport = () => {
    const printWindow = window.open('', '_blank');
    printWindow.document.write(`
      <!DOCTYPE html>
      <html>
      <head>
        <title>Learnora Progress Report</title>
        <style>
          body { font-family: system-ui, sans-serif; padding: 40px; max-width: 800px; margin: 0 auto; }
          h1 { color: #6366f1; border-bottom: 2px solid #6366f1; padding-bottom: 10px; }
          h2 { color: #333; margin-top: 30px; }
          .stat { display: inline-block; margin-right: 30px; }
          .stat-value { font-size: 32px; font-weight: bold; color: #6366f1; }
          .stat-label { color: #666; }
          table { width: 100%; border-collapse: collapse; margin: 20px 0; }
          th, td { padding: 12px; text-align: left; border-bottom: 1px solid #ddd; }
          th { background: #f5f5f5; }
          .grade-a { color: #10b981; }
          .grade-b { color: #6366f1; }
          .grade-c { color: #f59e0b; }
          .footer { margin-top: 40px; padding-top: 20px; border-top: 1px solid #ddd; color: #999; font-size: 12px; }
        </style>
      </head>
      <body>
        <h1>📚 Learnora Progress Report</h1>
        <p><strong>Student:</strong> ${reportData?.user?.name || 'John Doe'}</p>
        <p><strong>Email:</strong> ${reportData?.user?.email || 'john.doe@school.edu'}</p>
        <p><strong>Date:</strong> ${new Date().toLocaleDateString()}</p>
        
        <h2>📊 Learning Summary</h2>
        <div>
          <div class="stat">
            <div class="stat-value">${reportData?.stats?.totalHours || 0}h</div>
            <div class="stat-label">Total Study Time</div>
          </div>
          <div class="stat">
            <div class="stat-value">${reportData?.stats?.currentStreak || 0}</div>
            <div class="stat-label">Day Streak</div>
          </div>
          <div class="stat">
            <div class="stat-value">${reportData?.stats?.completedCourses || 0}</div>
            <div class="stat-label">Courses Completed</div>
          </div>
        </div>
        
        <h2>📚 Course Progress</h2>
        <table>
          <tr><th>Course</th><th>Progress</th><th>Rating</th></tr>
          ${(reportData?.courses || []).map(c => `
            <tr>
              <td>${c.name}</td>
              <td>${c.progress}%</td>
              <td>⭐ ${c.rating}</td>
            </tr>
          `).join('')}
        </table>
        
        <h2>📝 Quiz Results</h2>
        <table>
          <tr><th>Quiz</th><th>Score</th><th>Date</th></tr>
          ${(reportData?.quizzes || []).slice(0, 5).map(q => `
            <tr>
              <td>${q.title}</td>
              <td class="grade-b">${q.score || 'N/A'}</td>
              <td>${new Date(q.createdAt || Date.now()).toLocaleDateString()}</td>
            </tr>
          `).join('')}
        </table>
        
        <div class="footer">
          Generated by Learnora • ${new Date().toLocaleString()}
        </div>
      </body>
      </html>
    `);
    printWindow.document.close();
    printWindow.print();
  };

  return (
    <div style={{ marginBottom: '24px' }}>
      <div style={{ 
        background: 'var(--bg-secondary)', 
        border: '1px solid var(--border-color)', 
        borderRadius: 'var(--radius-xl)', 
        padding: '20px' 
      }}>
        <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '16px' }}>
          <div>
            <h3 style={{ fontSize: '16px', fontWeight: '700', margin: '0 0 4px 0', color: 'var(--text-primary)' }}>
              📄 Progress Report
            </h3>
            <p style={{ fontSize: '13px', color: 'var(--text-tertiary)', margin: 0 }}>
              Generate and print your learning progress
            </p>
          </div>
          <button 
            onClick={generateReport}
            disabled={isGenerating}
            style={{
              padding: '10px 20px',
              background: isGenerating ? 'var(--bg-tertiary)' : 'var(--accent-violet)',
              color: '#fff',
              border: 'none',
              borderRadius: '8px',
              cursor: isGenerating ? 'default' : 'pointer',
              fontWeight: '600',
              fontSize: '13px'
            }}
          >
            {isGenerating ? 'Generating...' : 'Generate Report'}
          </button>
        </div>
        
        {reportData && (
          <div style={{ 
            background: 'var(--bg-tertiary)', 
            borderRadius: '12px', 
            padding: '16px',
            marginTop: '16px'
          }}>
            <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '12px' }}>
              <span style={{ fontSize: '14px', fontWeight: '600', color: 'var(--text-primary)' }}>
                Report Ready
              </span>
              <button 
                onClick={printReport}
                style={{
                  padding: '8px 16px',
                  background: 'var(--primary-500)',
                  color: '#fff',
                  border: 'none',
                  borderRadius: '6px',
                  cursor: 'pointer',
                  fontWeight: '600',
                  fontSize: '12px',
                  display: 'flex',
                  alignItems: 'center',
                  gap: '6px'
                }}
              >
                🖨️ Print / Save PDF
              </button>
            </div>
            <div style={{ display: 'flex', gap: '20px', flexWrap: 'wrap' }}>
              <div style={{ textAlign: 'center' }}>
                <div style={{ fontSize: '24px', fontWeight: '700', color: 'var(--primary-500)' }}>{reportData.stats.totalHours}h</div>
                <div style={{ fontSize: '11px', color: 'var(--text-tertiary)' }}>Study Time</div>
              </div>
              <div style={{ textAlign: 'center' }}>
                <div style={{ fontSize: '24px', fontWeight: '700', color: 'var(--accent-orange)' }}>{reportData.stats.currentStreak}</div>
                <div style={{ fontSize: '11px', color: 'var(--text-tertiary)' }}>Day Streak</div>
              </div>
              <div style={{ textAlign: 'center' }}>
                <div style={{ fontSize: '24px', fontWeight: '700', color: 'var(--success)' }}>{reportData.courses.length}</div>
                <div style={{ fontSize: '11px', color: 'var(--text-tertiary)' }}>Courses</div>
              </div>
            </div>
          </div>
        )}
      </div>
    </div>
  );
};

window.ProgressReportGenerator = ProgressReportGenerator;
