// Icon Component - Uses Feather Icons with fallback to emoji
const Icon = ({ name, size = 24, color, strokeWidth = 2, className, style, ...props }) => {
  const iconRef = React.useRef(null);
  
  // Emoji fallback mapping for common icons
  const emojiMap = {
    'bot': '🤖',
    'sparkles': '✨',
    'message-square': '💬',
    'edit': '✏️',
    'trash': '🗑️',
    'trash-2': '🗑️',
    'panel-left-close': '◀',
    'panel-left-open': '▶',
    'send': '➤',
    'home': '🏠',
    'book-open': '📖',
    'file-text': '📄',
    'edit-3': '✏️',
    'help-circle': '❓',
    'layers': '📚',
    'bar-chart-2': '📊',
    'share-2': '🕸️',
    'message-circle': '💬',
    'settings': '⚙️',
    'corner-up-left': '↶',
    'corner-up-right': '↷',
    'save': '💾',
    'copy': '📋',
    'git-branch': '🌿',
    'columns': '▮▮',
    'lightbulb': '💡',
    'x': '✕',
    'plus': '➕',
    'minus': '➖',
    'check': '✓',
    'check-circle': '✅',
    'info': 'ℹ️',
    'alert-triangle': '⚠️',
    'alert-circle': '⚠️',
    'x-circle': '❌',
    'star': '⭐',
    'home': '🏠',
    'user': '👤',
    'settings': '⚙️',
    'menu': '☰',
    'search': '🔍',
    'bell': '🔔',
    'mail': '✉️',
    'phone': '📞',
    'map-pin': '📍',
    'calendar': '📅',
    'clock': '⏰',
    'book-open': '📖',
    'book': '📚',
    'layers': '🎴',
    'help-circle': '❓',
    'message-circle': '💬',
    'share': '📤',
    'download': '⬇️',
    'upload': '⬆️',
    'edit': '✏️',
    'trash': '🗑️',
    'more-vertical': '⋮',
    'more-horizontal': '⋯',
    'chevron-down': '▼',
    'chevron-up': '▲',
    'chevron-left': '◀',
    'chevron-right': '▶',
    'arrow-left': '←',
    'arrow-right': '→',
    'arrow-up': '↑',
    'arrow-down': '↓',
    'play': '▶️',
    'pause': '⏸️',
    'zap': '⚡',
    'sun': '☀️',
    'moon': '🌙',
    'sunrise': '🌅',
    'sunset': '🌇',
    'target': '🎯',
    'trending-up': '📈',
    'trending-down': '📉',
    'bar-chart-2': '📊',
    'pie-chart': '🥧',
    'activity': '📈',
    'wifi': '📶',
    'shield': '🛡️',
    'lock': '🔒',
    'unlock': '🔓',
    'eye': '👁️',
    'eye-off': '🚫',
    'file-text': '📄',
    'file': '📁',
    'folder': '📂',
    'image': '🖼️',
    'camera': '📷',
    'video': '🎥',
    'music': '🎵',
    'mic': '🎤',
    'award': '🏆',
    'trophy': '🏆',
    'medal': '🏅',
    'heart': '❤️',
    'thumbs-up': '👍',
    'smile': '😊',
    'frown': '😞',
    'meh': '😐',
    'loader': '⏳',
    'refresh-cw': '🔄',
    'rotate-cw': '↻',
    'rotate-ccw': '↺',
    'maximize': '⛶',
    'minimize': '🗗',
    'maximize-2': '⛶',
    'minimize-2': '🗗',
    'external-link': '↗️',
    'link': '🔗',
    'paperclip': '📎',
    'tag': '🏷️',
    'flag': '🚩',
    'bookmark': '🔖',
    'printer': '🖨️',
    'monitor': '🖥️',
    'smartphone': '📱',
    'tablet': '📱',
    'cpu': '🖥️',
    'server': '🖥️',
    'database': '🗄️',
    'cloud': '☁️',
    'cloud-rain': '🌧️',
    'cloud-snow': '🌨️',
    'wind': '💨',
    'umbrella': '☂️',
    'thermometer': '🌡️',
    'compass': '🧭',
    'globe': '🌐',
    'map': '🗺️',
    'navigation': '🧭',
    'hash': '#️⃣',
    'at-sign': '@️',
    'dollar-sign': '💲',
    'percent': '%️',
    'shopping-cart': '🛒',
    'shopping-bag': '🛍️',
    'gift': '🎁',
    'coffee': '☕',
    'utensils': '🍴',
    'car': '🚗',
    'truck': '🚚',
    'plane': '✈️',
    'train': '🚆',
    'bike': '🚲',
    'anchor': '⚓',
    'briefcase': '💼',
    'building': '🏢',
    'home-2': '🏠',
    'apartment': '🏢',
    'school': '🏫',
    'hospital': '🏥',
    'bank': '🏦',
    'church': '⛪',
    'factory': '🏭',
    'store': '🏪',
    'restaurant': '🍽️',
    'cafe': '☕',
    'bar': '🍺',
    'cinema': '🎬',
    'theater': '🎭',
    'museum': '🏛️',
    'library': '📚',
    'park': '🌳',
    'gym': '🏋️',
    'pool': '🏊',
    'spa': '♨️',
    'gas-station': '⛽',
    'parking': '🅿️',
    'traffic-light': '🚦',
    'stop-sign': '🛑',
    'construction': '🚧',
    'no-entry': '⛔',
    'warning': '⚠️',
    'info-2': 'ℹ️',
    'question': '❓',
    'help': '❓',
    'support': '🎧',
    'chat': '💬',
    'message-square': '💬',
    'inbox': '📥',
    'send': '📤',
    'reply': '↩️',
    'forward': '↪️',
    'copy': '📋',
    'paste': '📋',
    'scissors': '✂️',
    'align-left': '◀',
    'align-center': '▶◀',
    'align-right': '▶',
    'align-justify': '☰',
    'list': '☰',
    'grid': '▦',
    'layout': '▦',
    'sidebar': '▐',
    'columns': '▌▐',
    'rows': '▀▄',
    'move': '✥',
    'drag': '✥',
    'resize': '⇲',
    'crop': '⌖',
    'zoom-in': '🔍➕',
    'zoom-out': '🔍➖',
    'filter': '🔽',
    'sliders': '⚙️',
    'toggle-left': '◀',
    'toggle-right': '▶',
    'power': '⏻',
    'log-out': '🚪',
    'log-in': '🚪',
    'user-plus': '👤➕',
    'user-minus': '👤➖',
    'users': '👥',
    'group': '👥',
    'team': '👥',
    'github': '🐙',
    'gitlab': '🦊',
    'bitbucket': '🪣',
    'code': '💻',
    'terminal': '💻',
    'command': '⌘',
    'keyboard': '⌨️',
    'mouse': '🖱️',
    'headphones': '🎧',
    'headset': '🎧',
    'speaker': '🔊',
    'volume': '🔊',
    'volume-2': '🔊',
    'volume-x': '🔇',
    'mute': '🔇',
    'mic-off': '🚫🎤',
    'video-off': '🚫🎥',
    'camera-off': '🚫📷',
    'phone-off': '🚫📞',
    'bell-off': '🔕',
    'mail-off': '🚫✉️',
    'inbox-off': '🚫📥',
    'slash': '🚫',
    'ban': '🚫',
    'prohibited': '🚫'
  };
  
  React.useEffect(() => {
    if (!iconRef.current || !name) return;
    
    // Try to use Feather icons first
    try {
      if (window.feather && window.feather.icons && window.feather.icons[name]) {
        const svgString = window.feather.icons[name].toSvg({
          width: size,
          height: size,
          stroke: color || 'currentColor',
          'stroke-width': strokeWidth
        });
        
        if (typeof svgString === 'string') {
          iconRef.current.innerHTML = svgString;
          return;
        }
      }
    } catch (error) {
      console.warn(`Could not load icon: ${name}`, error);
    }
    
    // Fallback to emoji
    const emoji = emojiMap[name] || '•';
    if (iconRef.current) {
      iconRef.current.textContent = emoji;
      iconRef.current.style.fontSize = `${size}px`;
      iconRef.current.style.color = color || 'currentColor';
      iconRef.current.style.display = 'inline-flex';
      iconRef.current.style.alignItems = 'center';
      iconRef.current.style.justifyContent = 'center';
      iconRef.current.style.lineHeight = '1';
    }
  }, [name, size, color, strokeWidth]);
  
  return (
    <span 
      ref={iconRef} 
      className={`lucide-icon ${className || ''}`} 
      style={{ 
        width: size, 
        height: size, 
        display: 'inline-flex', 
        alignItems: 'center', 
        justifyContent: 'center',
        flexShrink: 0,
        ...style 
      }} 
      {...props} 
    />
  );
};

window.Icon = Icon;